# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.SmallIntegerField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
